# .env.production
VITE_APP_TITLE=My App

VITE_APP_API_KEY=production-api-key


# .env.development
VITE_APP_TITLE=My App
# VITE_APP_API_KEY=https://localhost:7055
VITE_APP_API_KEY=http://localhost:5113

VITE_APP_URL_APP_CLIENTE=http://localhost:3001



# VITE_APP_API_URL = 'http://localhost:3000'

VITE_APP_AUTH0_DOMAIN = 'dev-jf25eoy0grev3j2w.us.auth0.com'
VITE_APP_AUTH0_CLIENT_ID='UWAMocsTA1ChepUG7prlj8MF3zlirAFc'

VITE_APP_SUCURSAL_GENERICA = 1




# CLAVES PARA EL USO DE LOS ROLES 

VITE_APP_ROLE_ADMIN = 'Administrador'
VITE_APP_ROLE_SUCURSAL = 'Sucursal'
VITE_APP_ROLE_CLIENT = 'Cliente'

# CLAVE PARA USO DE MERCADO PAGO

# esta es la de la del vendedor de prueba de produccion
VITE_APP_PUBLIC_KEY = 'APP_USR-05307b8d-294c-4a02-9013-6d68bb65391b'


# esta es la de la aplicacion

# VITE_APP_PUBLIC_KEY = 'TEST-f51415c1-9863-4f01-ad6f-3b1578a76078'

#codigos de error
VITE_APP_API_ERROR_CODE_OK = 200
VITE_APP_API_ERROR_CODE_BAD_REQUEST = 400
VITE_APP_API_ERROR_CODE_UNAUTHORIZE = 401
VITE_APP_API_ERROR_CODE_FORBIDDEN = 403
VITE_APP_API_ERROR_CODE_NOT_FOUND = 404
VITE_APP_API_ERROR_CODE_INTERNAL_SERVER_ERROR = 500


VITE_APP_ESTADO_PEDIDO_TODOS = 0
VITE_APP_ESTADO_PEDIDO_INGRESADO = 1
VITE_APP_ESTADO_PEDIDO_ENVIADO = 2
VITE_APP_ESTADO_PEDIDO_ENTREGADO = 3
VITE_APP_ESTADO_PEDIDO_SIN_ENVIO = 4

VITE_APP_NETWORK_ERROR = "ERR_NETWORK"
